


//  -----------------------------------   ADVENTURE GENERATOR TABLES----------------------------------- 

d30sandbox.ag1 = {table: "AG1", tableName: "TRIGGER", results: [
"accusation",
"ambush",
"apparition",
"attack",
"conversation",
"destruction of object",
"diary",
"drawing",
"dream",
"encounter w/ NPC",
"escape",
"manuscript",
"map",
"message",
"item\, exotic",
"item\, mundane",
"oracle",
"plea",
"prophecy",
"public notice",
"reconnaissance",
"request",
"summoned by group",
"survivor",
"symbol",
"teleportation",
"transaction",
"trap",
"vision",
"warning"
]};

d30sandbox.ag2 = {table: "AG2", tableName: "MAJOR GOAL", results: [
"aid other hero(es)",
"break curse affecting persons(s)",
"break curse affecting location",
"capture fugitive",
"deal with growing threat",
"defend location",
"deliver message/object",
"discover secret",
"escort/protect object(s)/person(s)",
"investigate location",
"locate/track down NPC (ally/hero/villain)",
"maintain peace",
"prevent invasion",
"rally ally(allies)/form allegiance(s)",
"reclaim lost location (regain control of)",
"release person/creature from burden",
"rescue/free captive(s)/slave",
"root out spies/minions of evil",
"search for knowledge/evidence",
"solve mystery - disappearance of object",
"solve mystery - disappearance of person(s)",
"solve mystery - murder/death",
"solve mystery - theft",
"solve mystery - phenomenon",
"stop conflict",
"stop impending devastation",
"stop plot from coming to fruition",
"stop raids on location",
"stop strange phenomenon affecting location",
"stop villain from amassing power"
]};

d30sandbox.ag3 = {table: "AG3", tableName: "OBSTACLE TO GOAL", results: [
"acquire item",
"acquire knowledge",
"acquire key(s)/parts",
"awaken sleeping NPC",
"beat time limitation",
"clear name(s)/restore honor",
"compete in tournament",
"complete scavenger hunt",
"destroy item",
"escape location",
"explore location",
"find hidden/lost entrance",
"find hidden/lost location",
"find magic item/object",
"find way back to key location",
"fight for freedom",
"fix “broken” item",
"make long journey",
"make perilous journey",
"navigate labyrinth",
"navigate series of portals",
"pass series of tests",
"perform ritual",
"restore condition",
"race against antagonist(s)",
"reveal conspiracy",
"revive deceased NPC",
"solve puzzle/riddles",
"speak incantation",
"stop ritual"
]};

d30sandbox.ag4 = {table: "AG4", tableName: "LOCATION", results: [
"abbey",
"burial ground",
"catacombs",
"castle",
"cave/cavern",
"cemetary",
"chasm",
"citadel/keep",
"city",
"dungeon",
"farmstead",
"fortress",
"forest",
"hamlet",
"hill",
"island",
"mansion",
"mountain",
"outpost",
"palace",
"ruins",
"stronghold",
"temple",
"thorpe",
"tomb",
"tower",
"town",
"undercity",
"village",
"volcano"
]};

d30sandbox.ag5 = {table: "AG5", tableName: "LOCATION FEATURE", results: [
"altar",
"barracks",
"bridge",
"chapel",
"dais",
"door",
"fountain",
"garden",
"gallery",
"gate",
"plaza",
"laboratory",
"library",
"machine, clockwork",
"machine, magical",
"painting",
"pedestal",
"pit",
"pool",
"portal",
"sanctuary",
"sarcophagus",
"statue/idol",
"shrine",
"statuary",
"tapestry",
"throne",
"waterfall",
"well",
"workshop"
]};

d30sandbox.ag6 = {table: "AG6", tableName: "PHENOMENA", results: [
charm",
"darkness",
"decay",
"delusion",
"disease",
"disembodied voices",
"energy drain (hp)",
"energy drain (level)",
"fear",
"fever",
"fog/mist",
"fungi/mold/slime",
"hallucinations",
"hauntings",
"lights/colors",
"loss of memory",
"mania",
"monster plague",
"nightmares",
"noises/sounds",
"panic/paranoia",
"paralyzation",
"poisoning(s)",
"shadows",
"sickness",
"sightings of dead",
"sleep",
"strange vegetation",
"strange weather",
"transformation
]};

d30sandbox.ag7 = {table: "AG7", tableName: "VILLAIN GOAL/REASON", results: [
"amusement/boredom",
"avoid loss/pain",
"corruption",
"debt owed",
"derangement/insanity",
"destiny",
"domination/control",
"eliminate species",
"enslavement",
"envy",
"experimentation",
"fear",
"forgotten reason",
"guilt",
"greed",
"hatred",
"honor",
"immortality",
"ideology (strange)",
"loyalty (misplaced)",
"mass destruction",
"mischief",
"noble goal, extreme measures",
"power",
"pride/vanity",
"pure evil",
"revenge",
"self-preservation/survival",
"serves higher “boss”",
"utopia (at all costs)"
]};

d30sandbox.ag8 = {table: "AG8", tableName: "ARTIFACT/RELIC", results: [
"amulet",
"bowl/brazier/censer",
"box",
"bracers",
"candle",
"codex/manual/tome",
"cube",
"cup",
"figurine/idol",
"flask",
"gem/jewel",
"grimoire",
"horn/instrument",
"mask",
"medallion",
"mirror",
"necklace",
"orb/sphere",
"pearl",
"potion",
"ring",
"rod",
"scarab",
"scepter",
"spellbook",
"staff",
"stone",
"talisman",
"wand",
"weapon"
]};

d30sandbox.ag9 = {table: "AG9", tableName: "THEME", results: [
"blood",
"darkness/night",
"death",
"destiny",
"doom",
"freedom",
"forbidden",
"enchantment",
"evil",
"flame(s)",
"glory",
"gold",
"greed",
"innocence",
"immortality",
"judgement",
"justice",
"life",
"light/day",
"madness",
"mystery",
"power",
"rebirth",
"revenge",
"shadow",
"terror",
"treasure",
"vengeance",
"wonder",
"wrath"
]};

d30sandbox.ag10 = {table: "AG10", tableName: "KEY NPC", results: [
"cleric",
"druid/cleric*",
"fighter",
"paladin/fighter*",
"ranger/dwarf*",
"magic-user",
"illusionist/magic-user",
"thief",
"assassin/halfling*",
"monk/elf*",
"animal trainer",
"hermit",
"merchant", 									//(see NPCO2a, p.42)
"misc. NPC" 									//(see NPCO2c, p.42)
"pilgrim (as 1st-level cleric)",
"sage",											//(see pp.44-45)
"scribe",
"spy (as thief)",
"smith",
"tradesman",									// (see NPCO2b, p.42)
"king",
"queen",
"queen mother",
"noble",										// (see NPCN1/NPCN2, p.43)
"noble household",								// (see NPCH, p.43)
"noble teacher",								//(see NPCT, p.43)
"castle employee",								// (see NPCJ, p.43)",
"soldier",
"slave",
"peasant"
]};
