

{climate:"tropical",terrain:"hills", weather: [ {month: 1, tempAv: 60,"–"}, {month: 2, tempAv: 65,"I"}, {month: 3, tempAv: 70,"–"}, {month: 4, tempAv: 75,"I"}, {month: 5, tempAv:80,"II"}, {month: 6, tempAv: 85,"I"}, {month: 7, tempAv: 95,"I"}, {month: 8, tempAv:100,"III"}, {month: 9, tempAv:95,"II"}, {month: 10, tempAv: 80,"–"}, {month: 11, tempAv:70,"I"}, {month: 12, tempAv:65,"–"},] }
{climate:"tropical",terrain:"mountains",weather: [ {month: 1, tempAv: 65,"I"}, {month: 2, tempAv: 65,"III"}, {month: 3, tempAv: 70,"II"}, {month: 4, tempAv: 75,"III"}, {month: 5, tempAv:80,"IV"}, {month: 6, tempAv: 85,"IV"}, {month: 7, tempAv: 90,"I"}, {month: 8, tempAv:95,"III"}, {month: 9, tempAv:95,"II"}, {month: 10, tempAv: 90,"III"}, {month: 11, tempAv:80,"IV"}, {month: 12, tempAv:70,"IV"},] }
{climate:"tropical",terrain:"forest",weather: [ {month: 1, tempAv: 80,"III"}, {month: 2, tempAv: 80,"V"}, {month: 3, tempAv: 80,"IV"}, {month: 4, tempAv:85,"III"}, {month: 5, tempAv: 85,"V"}, {month: 6, tempAv:85,"IV"}, {month: 7, tempAv:90,"III"}, {month: 8, tempAv: 90,"V"}, {month: 9, tempAv: 90,"IV"}, {month: 10, tempAv:85,"III"}, {month: 11, tempAv:80,"V"}, {month: 12, tempAv:80,"IV"},] }
{climate:"tropical",terrain:"plains",weather: [ {month: 1, tempAv: 65,"–"}, {month: 2, tempAv: 70,"I"}, {month: 3, tempAv: 75,"–"}, {month: 4, tempAv: 80,"II"}, {month: 5, tempAv:85,"IV"}, {month: 6, tempAv: 90,"III"}, {month: 7, tempAv: 95,"III"}, {month: 8, tempAv:95,"IV"}, {month: 9, tempAv:90,"III"}, {month: 10, tempAv: 85,"II"}, {month: 11, tempAv:80,"IV"}, {month: 12, tempAv:75,"III"},] }
{climate:"tropical",terrain:"swamp", weather: [ {month: 1, tempAv: 65,"–"}, {month: 2, tempAv: 70,"II"}, {month: 3, tempAv: 75,"I"}, {month: 4, tempAv: 80,"III"}, {month: 5, tempAv:85,"IV"}, {month: 6, tempAv: 90,"IV"}, {month: 7, tempAv: 95,"III"}, {month: 8, tempAv:95,"IV"}, {month: 9, tempAv:90,"III"}, {month: 10, tempAv: 85,"II"}, {month: 11, tempAv:80,"III"}, {month: 12, tempAv:75,"III"},] }
{climate:"tropical",terrain:"desert",weather: [ {month: 1, tempAv: 70,"–"}, {month: 2, tempAv: 75,"I"}, {month: 3, tempAv: 80,"–"}, {month: 4, tempAv: 80,"–"}, {month: 5, tempAv:85,"II"}, {month: 6, tempAv: 85,"I"}, {month: 7, tempAv: 90,"–"}, {month: 8, tempAv:95,"I"}, {month: 9, tempAv:90,"–"}, {month: 10, tempAv: 85,"–"}, {month: 11, tempAv:80,"I"}, {month: 12, tempAv:75,"–"},] }
{climate:"tropical",terrain:"coast", weather: [ {month: 1, tempAv: 75,"–"}, {month: 2, tempAv: 75,"I"}, {month: 3, tempAv: 80,"–"}, {month: 4, tempAv: 85,"II"}, {month: 5, tempAv:85,"V"}, {month: 6, tempAv: 90,"III"}, {month: 7, tempAv: 90,"IV"}, {month: 8, tempAv:90,"V"}, {month: 9, tempAv:85,"V"}, {month: 10, tempAv: 75,"I"}, {month: 11, tempAv:75,"II"}, {month: 12, tempAv:70,"I"},] }

{climate:"subtropical", terrain:"hills",weather: [ {month: 1, tempAv: 60,"I"}, {month: 2, tempAv: 65,"II"}, {month: 3, tempAv: 70,"II"}, {month: 4, tempAv: 75,"II"}, {month: 5, tempAv:75,"IV"}, {month: 6, tempAv: 80,"III"}, {month: 7, tempAv: 80,"II"}, {month: 8, tempAv:85,"IV"}, {month: 9, tempAv:75,"III"}, {month: 10, tempAv: 70,"I"}, {month: 11, tempAv:65,"III"}, {month: 12, tempAv:60,"II"},] }
{climate:"subtropical", terrain:"mountains", weather: [ {month: 1, tempAv: 55,"I"}, {month: 2, tempAv: 60,"III"}, {month: 3, tempAv: 65,"II"}, {month: 4, tempAv: 70,"II"}, {month: 5, tempAv:70,"IV"}, {month: 6, tempAv: 75,"III"}, {month: 7, tempAv: 65,"II"}, {month: 8, tempAv:60,"III"}, {month: 9, tempAv:65,"III"}, {month: 10, tempAv: 60,"I"}, {month: 11, tempAv:60,"III"}, {month: 12, tempAv:55,"II"},] }
{climate:"subtropical", terrain:"forest",weather: [ {month: 1, tempAv: 75,"III"}, {month: 2, tempAv: 70,"IV"}, {month: 3, tempAv: 75,"IV"}, {month: 4, tempAv:75,"III"}, {month: 5, tempAv: 80,"V"}, {month: 6, tempAv:85,"IV"}, {month: 7, tempAv:85,"III"}, {month: 8, tempAv: 85,"V"}, {month: 9, tempAv: 80,"IV"}, {month: 10, tempAv:80,"III"}, {month: 11, tempAv:75,"IV"}, {month: 12, tempAv:75,"IV"},] }
{climate:"subtropical", terrain:"plains",weather: [ {month: 1, tempAv: 60,"–"}, {month: 2, tempAv: 65,"II"}, {month: 3, tempAv: 70,"I"}, {month: 4, tempAv: 75,"I"}, {month: 5, tempAv:80,"IV"}, {month: 6, tempAv: 85,"II"}, {month: 7, tempAv: 90,"I"}, {month: 8, tempAv:90,"III"}, {month: 9, tempAv:95,"II"}, {month: 10, tempAv: 85,"–"}, {month: 11, tempAv:75,"II"}, {month: 12, tempAv:65,"I"},] }
{climate:"subtropical", terrain:"swamp",weather: [ {month: 1, tempAv: 60,"I"}, {month: 2, tempAv: 65,"II"}, {month: 3, tempAv: 70,"II"}, {month: 4, tempAv: 75,"I"}, {month: 5, tempAv:80,"III"}, {month: 6, tempAv: 85,"II"}, {month: 7, tempAv: 90,"I"}, {month: 8, tempAv:90,"IV"}, {month: 9, tempAv:85,"II"}, {month: 10, tempAv: 85,"I"}, {month: 11, tempAv:70,"II"}, {month: 12, tempAv:65,"II"},] }
{climate:"subtropical", terrain:"desert",weather: [ {month: 1, tempAv: 60,"–"}, {month: 2, tempAv: 65,"I"}, {month: 3, tempAv: 75,"–"}, {month: 4, tempAv: 75,"–"}, {month: 5, tempAv:80,"I"}, {month: 6, tempAv: 85,"–"}, {month: 7, tempAv: 90,"–"}, {month: 8, tempAv:90,"–"}, {month: 9, tempAv:85,"–"}, {month: 10, tempAv: 80,"–"}, {month: 11, tempAv:75,"I"}, {month: 12, tempAv:70,"–"},] }
{climate:"subtropical", terrain:"coast",weather: [ {month: 1, tempAv: 55,"I"}, {month: 2, tempAv: 60,"III"}, {month: 3, tempAv: 65,"II"}, {month: 4, tempAv: 65,"II"}, {month: 5, tempAv:75,"IV"}, {month: 6, tempAv: 85,"III"}, {month: 7, tempAv: 75,"II"}, {month: 8, tempAv:75,"V"}, {month: 9, tempAv:70,"III"}, {month: 10, tempAv: 70,"–"}, {month: 11, tempAv:65,"II"}, {month: 12, tempAv:60,"I"},] }

{climate:"temperate", terrain:"hills", weather: [ {month: 1, tempAv: 25,"I"}, {month: 2, tempAv: 30,"III"}, {month: 3, tempAv: 40,"II"}, {month: 4, tempAv: 50,"II"}, {month: 5, tempAv:60,"IV"}, {month: 6, tempAv: 70,"III"}, {month: 7, tempAv: 75,"II"}, {month: 8, tempAv:80,"IV"}, {month: 9, tempAv:70,"III"}, {month: 10, tempAv: 55,"I"}, {month: 11, tempAv:40,"III"}, {month: 12, tempAv:30,"II"},] }
{climate:"temperate", terrain:"mountains",weather: [ {month: 1, tempAv: 25,"–"}, {month: 2, tempAv: 25,"III"}, {month: 3, tempAv: 30,"II"}, {month: 4, tempAv: 40,"–"}, {month: 5, tempAv:50,"III"}, {month: 6, tempAv: 65,"II"}, {month: 7, tempAv: 70,"–"}, {month: 8, tempAv:70,"II"}, {month: 9, tempAv:60,"I"}, {month: 10, tempAv: 50,"–"}, {month: 11, tempAv:40,"III"}, {month: 12, tempAv:30,"II"},] }
{climate:"temperate", terrain:"forest",weather: [ {month: 1, tempAv: 20,"I"}, {month: 2, tempAv: 15,"III"}, {month: 3, tempAv: 40,"II"}, {month: 4, tempAv: 50,"II"}, {month: 5, tempAv:60,"IV"}, {month: 6, tempAv: 65,"III"}, {month: 7, tempAv: 75,"II"}, {month: 8, tempAv:75,"III"}, {month: 9, tempAv:65,"III"}, {month: 10, tempAv: 60,"I"}, {month: 11, tempAv:35,"III"}, {month: 12, tempAv:30,"III"},] }
{climate:"temperate", terrain:"plains",weather: [ {month: 1, tempAv: 15,"–"}, {month: 2, tempAv: 20,"II"}, {month: 3, tempAv: 40,"I"}, {month: 4, tempAv: 50,"II"}, {month: 5, tempAv:60,"IV"}, {month: 6, tempAv: 65,"III"}, {month: 7, tempAv: 75,"II"}, {month: 8, tempAv:75,"IV"}, {month: 9, tempAv:65,"III"}, {month: 10, tempAv: 50,"I"}, {month: 11, tempAv:40,"III"}, {month: 12, tempAv:30,"II"},] }
{climate:"temperate", terrain:"swamp", weather: [ {month: 1, tempAv: 30,"I"}, {month: 2, tempAv: 35,"III"}, {month: 3, tempAv: 40,"II"}, {month: 4, tempAv: 50,"II"}, {month: 5, tempAv:60,"IV"}, {month: 6, tempAv: 65,"II"}, {month: 7, tempAv: 75,"II"}, {month: 8, tempAv:75,"IV"}, {month: 9, tempAv:75,"III"}, {month: 10, tempAv: 60,"–"}, {month: 11, tempAv:50,"III"}, {month: 12, tempAv:40,"II"},] }
{climate:"temperate", terrain:"desert",weather: [ {month: 1, tempAv: 55,"–"}, {month: 2, tempAv: 55,"I"}, {month: 3, tempAv: 60,"–"}, {month: 4, tempAv: 65,"–"}, {month: 5, tempAv:70,"I"}, {month: 6, tempAv: 80,"–"}, {month: 7, tempAv: 90,"–"}, {month: 8, tempAv:90,"I"}, {month: 9, tempAv:85,"–"}, {month: 10, tempAv: 75,"–"}, {month: 11, tempAv:70,"–"}, {month: 12, tempAv:55,"–"},] }
{climate:"temperate", terrain:"coast", weather: [ {month: 1, tempAv: 30,"II"}, {month: 2, tempAv: 40,"IV"}, {month: 3, tempAv: 45,"III"}, {month: 4, tempAv: 50,"I"}, {month: 5, tempAv:55,"III"}, {month: 6, tempAv: 65,"II"}, {month: 7, tempAv: 65,"–"}, {month: 8, tempAv:65,"II"}, {month: 9, tempAv:60,"I"}, {month: 10, tempAv: 50,"II"}, {month: 11, tempAv:40,"IV"}, {month: 12, tempAv:35,"III"},] }

{climate:"subarctic", terrain:"hills", weather: [ {month: 1, tempAv: -5,"–"}, {month: 2, tempAv: -5,"I"}, {month: 3, tempAv: 10,"I"}, {month: 4, tempAv: 15,"–"}, {month: 5, tempAv:40,"II"}, {month: 6, tempAv: 50,"I"}, {month: 7, tempAv: 55,"I"}, {month: 8, tempAv:55,"II"}, {month: 9, tempAv:40,"II"}, {month: 10, tempAv: 30,"–"}, {month: 11, tempAv:15,"II"}, {month: 12, tempAv:10,"I"},] }
{climate:"subarctic", terrain:"mountains",weather: [ {month: 1, tempAv: -5,"–"}, {month: 2, tempAv: -5,"I"}, {month: 3, tempAv: 15,"I"}, {month: 4, tempAv: 15,"I"}, {month: 5, tempAv:30,"III"}, {month: 6, tempAv: 40,"II"}, {month: 7, tempAv: 50,"I"}, {month: 8, tempAv:55,"II"}, {month: 9, tempAv:40,"I"}, {month: 10, tempAv: 30,"–"}, {month: 11, tempAv:15,"II"}, {month: 12, tempAv:10,"I"},] }
{climate:"subarctic", terrain:"forest",weather: [ {month: 1, tempAv: 5,"–"}, {month: 2, tempAv: 5,"II"}, {month: 3, tempAv: 15,"I"}, {month: 4, tempAv: 30,"I"}, {month: 5, tempAv:40,"III"}, {month: 6, tempAv: 50,"II"}, {month: 7, tempAv: 55,"I"}, {month: 8, tempAv:55,"III"}, {month: 9, tempAv:40,"II"}, {month: 10, tempAv: 30,"I"}, {month: 11, tempAv:20,"II"}, {month: 12, tempAv:15,"I"},] }
{climate:"subarctic", terrain:"plains",weather: [ {month: 1, tempAv: -5,"–"}, {month: 2, tempAv: -5,"II"}, {month: 3, tempAv: 5,"I"}, {month: 4, tempAv:15,"I"}, {month: 5, tempAv: 40,"III"}, {month: 6, tempAv:50,"II"}, {month: 7, tempAv:55,"I"}, {month: 8, tempAv: 55,"III"}, {month: 9, tempAv: 40,"II"}, {month: 10, tempAv:25,"I"}, {month: 11, tempAv:5,"II"}, {month: 12, tempAv:-5,"I"},] }
{climate:"subarctic", terrain:"swamp", weather: [ {month: 1, tempAv: -5,"–"}, {month: 2, tempAv: -5,"II"}, {month: 3, tempAv: 5,"I"}, {month: 4, tempAv:20,"I"}, {month: 5, tempAv: 40,"III"}, {month: 6, tempAv:50,"II"}, {month: 7, tempAv:55,"I"}, {month: 8, tempAv: 55,"II"}, {month: 9, tempAv: 40,"II"}, {month: 10, tempAv:25,"I"}, {month: 11, tempAv:10,"II"}, {month: 12, tempAv:0,"II"},] }
{climate:"subarctic", terrain:"desert",weather: [ {month: 1, tempAv: -5,"–"}, {month: 2, tempAv: -5,"I"}, {month: 3, tempAv: 5,"–"}, {month: 4, tempAv:15,"–"}, {month: 5, tempAv: 40,"–"}, {month: 6, tempAv:50,"I"}, {month: 7, tempAv:55,"–"}, {month: 8, tempAv: 55,"–"}, {month: 9, tempAv: 40,"I"}, {month: 10, tempAv:25,"–"}, {month: 11, tempAv:5,"I"}, {month: 12, tempAv:-5,"–"},] }
{climate:"subarctic", terrain:"coast", weather: [ {month: 1, tempAv: 15,"–"}, {month: 2, tempAv: 20,"I"}, {month: 3, tempAv: 25,"I"}, {month: 4, tempAv: 30,"–"}, {month: 5, tempAv:40,"II"}, {month: 6, tempAv: 50,"I"}, {month: 7, tempAv: 55,"I"}, {month: 8, tempAv:55,"III"}, {month: 9, tempAv:50,"II"}, {month: 10, tempAv: 40,"–"}, {month: 11, tempAv:25,"II"}, {month: 12, tempAv:15,"I"},] }

{climate:"arctic",terrain:"hills", weather: [ {month: 1, tempAv: -15,"–"}, {month: 2, tempAv: -20,"–"}, {month: 3, tempAv: -10,"I"}, {month: 4, tempAv: -5,"–"}, {month: 5, tempAv:5,"II"}, {month: 6, tempAv: 15,"I"}, {month: 7, tempAv: 20,"–"}, {month: 8, tempAv:20,"–"}, {month: 9, tempAv:15,"I"}, {month: 10, tempAv: 5,"–"}, {month: 11, tempAv:0,"–"}, {month: 12, tempAv:-10,"I"},] }
{climate:"arctic",terrain:"mountains",weather: [ {month: 1, tempAv: -15,"–"}, {month: 2, tempAv: -20,"–"}, {month: 3, tempAv: -10,"I"}, {month: 4, tempAv: -5,"–"}, {month: 5, tempAv:5,"–"}, {month: 6, tempAv: 15,"I"}, {month: 7, tempAv: 20,"–"}, {month: 8, tempAv:20,"–"}, {month: 9, tempAv:15,"I"}, {month: 10, tempAv: 5,"–"}, {month: 11, tempAv:0,"–"}, {month: 12, tempAv:-10,"I"},] }
{climate:"arctic",terrain:"plains",weather: [ {month: 1, tempAv: -10,"–"}, {month: 2, tempAv: -15,"I"}, {month: 3, tempAv: -5,"I"}, {month: 4, tempAv: 5,"–"}, {month: 5, tempAv:15,"II"}, {month: 6, tempAv: 30,"I"}, {month: 7, tempAv: 40,"–"}, {month: 8, tempAv:40,"III"}, {month: 9, tempAv:25,"II"}, {month: 10, tempAv: 15,"–"}, {month: 11, tempAv:-5,"I"}, {month: 12, tempAv:-15,"I"},] }
{climate:"arctic",terrain:"desert",weather: [ {month: 1, tempAv: -10,"–"}, {month: 2, tempAv: -15,"I"}, {month: 3, tempAv: -5,"–"}, {month: 4, tempAv: 5,"–"}, {month: 5, tempAv:15,"I"}, {month: 6, tempAv: 30,"–"}, {month: 7, tempAv: 40,"–"}, {month: 8, tempAv:40,"I"}, {month: 9, tempAv:25,"–"}, {month: 10, tempAv: 15,"–"}, {month: 11, tempAv:-5,"I"}, {month: 12, tempAv:-15,"–"},] }
{climate:"arctic",terrain:"coast", weather: [ {month: 1, tempAv: -5,"–"}, {month: 2, tempAv: -15,"I"}, {month: 3, tempAv: -5,"–"}, {month: 4, tempAv: 5,"–"}, {month: 5, tempAv:15,"–"}, {month: 6, tempAv: 30,"I"}, {month: 7, tempAv: 40,"–"}, {month: 8, tempAv:40,"II"}, {month: 9, tempAv:25,"I"}, {month: 10, tempAv: 15,"–"}, {month: 11, tempAv:0,"I"}, {month: 12, tempAv:-10,"I"},] }
